### ISSUE TITLE
Troubles with DeepQLearning

### ISSUE THREAD

**Issue by HappyDay-design** [YZhang-Genghis/deep-reinforcement-learning-pedestrian-signal-design#1]
Hello
Thank you for sharing your code.

I could run two models with fixed time and pedestrian 

But I had errors when running training_main.py in DEEPQLEARNING.

----- Episode 1 of 200
Traceback (most recent call last):
  File "/home/osboxes/anaconda3/envs/Hung/lib/python3.7/site-packages/sumolib/net/__init__.py", line 831, in readNet
    parse(gzip.open(filename), netreader)
  File "/home/osboxes/anaconda3/envs/Hung/lib/python3.7/gzip.py", line 58, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/osboxes/anaconda3/envs/Hung/lib/python3.7/gzip.py", line 168, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'intersection\\pedcrossing.net.xml'

I tried to modify in generator.py but I can not run your models

**Comment by HappyDay-design** [comment]
I modify your file and i can run your model
 
change intersection to Intersection in utils.py
change \\\ to / in generator.py

**Comment by ClimbingMachine** [comment]
> I modify your file and i can run your model
> 
> change intersection to Intersection in utils.py change \\ to / in generator.py

Thank you for pointing this out. I ran the code locally before and forgot to change the name of the directory. 
Glad it works now, and let me know if I can help with anything.

**Comment by ClimbingMachine** [comment]
Have been updated based on @TrinhTuanHung2021 comments. Closed for inactivity.
